# Python envs for git hooks, tablegeneration etc.
name: tex-flow-py37
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - imageio=2.9.0=py_0
  - jpeg=9b=he5867d9_2
  - matplotlib=3.3.4=py37hecd8cb5_0
  - matplotlib-base=3.3.4=py37h8b3ea08_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37ha059aab_0
  - mkl_random=1.1.1=py37h959d312_0
  - pandas=1.2.3=py37hb2f4e1b_0
  - pillow=8.1.2=py37h5270095_0
  - pip=21.0.1=py37hecd8cb5_0
  - python=3.7.10=h88f2d9e_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytorch=1.8.0=py3.7_0
  - pyyaml=5.4.1=py37h9ed2024_1
  - scikit-image=0.17.2=py37h81aa140_0
  - scikit-learn=0.24.1=py37hb2f4e1b_0
  - scipy=1.6.1=py37h2515648_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - six=1.15.0=py37hecd8cb5_0
  - torchaudio=0.8.0=py37
  - torchvision=0.9.0=py37_cpu
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - --extra-index-url  https://pypi.apple.com/simple
    - absl-py==0.12.0
    - dm-tree==0.1.5
    - gitpython==3.1.14
    - markdown==3.3.4
    - pre-commit==2.15.0
    - seaborn==0.11.2
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - tqdm==4.59.0
    - zipp==3.4.1
