# latexindent local settings https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html
maxNumberOfBackUps: 2   # Actually keeps 0, 1, 2
cycleThroughBackUps: 1  # First copies 1 -> 2, 0 -> 1, then backs up to 0
